remote_theme: sproogen/modern-resume-theme
title: Pavan Sai Eshwar Chandra Boppana
name: Pavan Sai Eshwar Chandra Boppana
job_title: Senior Deep Learning Engineer
email: 18pavansai@gmail.com
phone: +65 81242224
location: Singapore

# optional links
# github_username: pavansai018
# linkedin_username: your-linkedin
